### ISSUE TITLE
Port extension to Ulauncher 5

### ISSUE THREAD

**Issue by vipau** [isacikgoz/ukill#4]
Ulauncher 5 (of which development builds are already available) will ship the Python 3 version only. As a result, all extensions have to be ported to Python 3, and also the new Ulauncher Extension API v2.

See [more details here](http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0)

**Comment by isacikgoz** [comment]
Thanks for the warning @paualberto. I will be looking into this.

**Comment by godismyjudge95** [comment]
Ulauncher just released a new version and it broke this extension.
See here:
https://mailchi.mp/fbb4b54c426a/ulauncher-is-migrating-to-python-3-changes-to-extension-api-and-more

And here:
http://docs.ulauncher.io/en/latest/extensions/migration.html

**Comment by isacikgoz** [comment]
Thanks for reporting this issue @paualberto and @godismyjudge95. I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.
